channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - cudatoolkit>=10.1
  - pytorch
  - torchvision
  - pip
  - scikit-learn
  - scikit-image
  - scipy
  - matplotlib
  - h5py
  - pandas
  - jupyter
  - pip:
    - nuscenes-devkit==1.1.0
    - pytorch-lightning>=1.5.10
    - torchmetrics>=0.7.0
    - hydra-core>=1.1.0
    - hydra-colorlog>=1.1.0
    - fairscale
    - opencv-python
    - pyquaternion
    - wandb
    - efficientnet_pytorch==0.7.1
    - click             # for easy script cli
    - einops            # for easy implementation of transformer block
    - python-dotenv     # loading env variables from .env file
    - rich              # beautiful text formatting in terminal
