resize_lim: [0.3, 0.3]
final_dim: [224,480]
rot_lim: [0., 0.]
H: 900
W: 1600
rand_flip: False
bot_pct_lim: [0.8295, 0.8295]
cams:
  - 'CAM_FRONT_LEFT'
  - 'CAM_FRONT'
  - 'CAM_FRONT_RIGHT'
  - 'CAM_BACK_LEFT'
  - 'CAM_BACK'
  - 'CAM_BACK_RIGHT'
Ncams: 6
min_visibility: 1
update_intrinsics: True