# @package _global_


defaults:
  - default.yaml

trainer:
  gpus: 1
  max_epochs: 3000
  limit_train_batches: 1
  limit_val_batches: 1
  limit_test_batches: 1
  log_every_n_steps: 1
  strategy: null
  check_val_every_n_epoch: 1000000
  track_grad_norm: -1

datamodule:
  batch_size: 1
  train_shuffle: False

scheduler:
  step_size: 1000

logger:
  tensorboard:
    save_dir: ${oc.env:DEBUG_SAVEDIR}


